name: JavaDoc

on:
  push:
    branches:
      - 2.2.X
  workflow_dispatch:

jobs:
  javadoc:
    runs-on: ubuntu-latest
    
    env:
      JDK_VERSION: 17
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo Java Version
        run: >
            java -version
      - name: Generate JavaDoc
        run: mvn javadoc:javadoc
      - name: Deploy JavaDoc
        uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: datasketches-memory-java8/target/site/apidocs
          target-folder: docs/${{ github.ref_name }}
          branch: gh-pages
