name: JavaDoc

on:
  push:
    branches:
      - 4.0.X
      - main
  workflow_dispatch:

jobs:
  javadoc:
    runs-on: ubuntu-latest
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout Java
        uses: actions/checkout@v4
        with:
          repository: apache/datasketches-memory
          path: java

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Echo Java Version
        run:  java -version

      - name: Generate JavaDoc
        run: mvn javadoc:javadoc

      - name: Deploy JavaDoc
        uses: JamesIves/github-pages-deploy-action@5dc1d5a192aeb5ab5b7d5a77b7d36aea4a7f5c92
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: target/site/apidocs
          target-folder: docs/${{ github.ref_name }}
          branch: gh-pages
