name: Placeholder for Manual Trigger

# Prototype skeleton to register the workflow name and manual dispatch 
# switch with GitHub's UI on the default branch. 
# This placeholder allows full testing inside development branches 
#  for this .github/workflows/<filename>.
# 
# 1. Create a temporary branch off of /main/.
# 2. In that branch create a new file with the eventual target workflow filename.
# 3. Push a copy the contents of the placeholder.yml to the new file.
# 4. Create a PR to merge the contents of the temp file into /main/.
# 4. Develop the content of the target workflow in your development branch. 
#    Now you can use the worflow_dispatch in your development branch.
# 5. When you are done, create a PR to merge the new workflow into /main/.
# 6. Do not overwrite the placeholder.yml. It is there for the next workflow.

on:
  workflow_dispatch:

jobs:
  placeholder:
    runs-on: ubuntu-latest
    steps:
      - name: Prototype Placeholder
        run: echo "This is a placeholder. Run this workflow from your feature branch to execute the real deployment logic."
